### ISSUE TITLE
attach papers to notes

### ISSUE THREAD

**Issue by DahlitzFlorian** [jldiaz/cookiecutter-mkdocs-notes#2]
What do you think about adding a functionality to attach the paper/book (if a digital copy is available) to the notes? Something like having a central location for all papers/books and auto-detecting and attaching them based on the file name (should be the same as the notes name).

**Comment by jldiaz** [comment]
Thank  you for your suggestion!

Currently the template supports the presence of a `url` field in the yaml metadata header. If present, the title will provide a clickable "link" sytmbol  (↗️) which leads to the given url.

This feature is meant to link the notes to the online paper (or to a copy in Dropbox, OneDrive, etc. if  you have the link). It can be used also to link to any other file in the `docs` folder, if you use the relative path.

So, your suggestion requires simply a way to automate the creation of this `url` field, which currently is manual, and done by the author of the note. I don't think it is worth implementing that automation. The current mechanism is more flexible because it allows you to link to "external" sources, as well to internal ones, and it is not so much trouble to manually add the url.

**Comment by DahlitzFlorian** [comment]
Oh, didn't see that. But your argumentation makes sense to me. Thanks!
